### PR TITLE
Adding MaxResvJobs to the association list

### PR DESCRIPTION
**Pull request by gskouson**
This should add the ability for a MaxResvJobs attribute to allow a limit of the number of jobs that can be running before we stop reserving slots in the backfill map for the remaining pending jobs.

This adds functionality similar to the soft job limit provided by Moab.

### CODE REVIEW

**Comment by dannyauble** [comment]
Hey Gary, this looks pretty good!  A couple of things though

1. We usually don't like to add to the middle of an enum to protect backwards compatibility (slurm.h.in).
2. Also I believe the new function in acct_policy.c could break on the first max_resv_jobs instead of traversing the entire list every time.
3. There are a couple of long lines in sacctmgr.c as well.

But all in all this looks pretty good.

Did you think of adding this for the QOS as well?

If you wouldn't mind opening a bug on this http://bugs.schedmd.com (we don't use github for pull requests) that would be great and we will see if we can get this in on the next release.

**Comment by gskouson** [comment]
Thanks for the feedback.

I wondered about the backwards compatibility with the enum, but put it where it logically fit in my mind.  It makes sense to put it at the end.

For the function in acct_policy.c, I was trying to follow the same logic from the acct_policy_job_runnable_pre_select function that checks the assoc->max_jobs.  It does a "goto end_it", once we find we're over the limit, but I didn't quite follow the how one level may override the limit from another level.  I just figured I'd use the same logic in my function.  I figured if we found an association that we were over the limit on,  we might as well break out and skip the other checks.

I started to fix the long lines, in sacctmgr.c, but didn't get back to it.

I thought about adding it to QOS as well, but wanted to make sure I had something that worked on the association first before doing that.  I don't think it would be too hard to put in the rest of the stuff for QOS, but I'd have to look at the logic a bit better to make sure I have the proper precedence on which checks go where.

**Comment by gskouson** [comment]
Opened Bug 2432

**Comment by dannyauble** [comment]
Thanks!

**Pull request closed without merging**
