### PR TITLE
spank_set_item function

### PR DESCRIPTION
**Pull request by supermanue**
This pull request includes

spank_err_t spank_set_item (spank_t spank, spank_item_t item, ...);

a function that allows to modify parameters analog to spank_get_item. At this moment it only allows modifying S_JOB_ENV, but can be extended as needed.

As a small additional modification,  a new parameter S_CHECKPOINT_DIR has been added and included on the spank_get_item function

### CODE REVIEW

**Comment by davidbigagli** [comment]
Hi,
    couple of comments about the patch. There is no testplugin directory in the main source so perhaps
that should be removed from the patch. The plugstack code uses xmalloc()/xfree() for memory management instead of malloc()/free() could you fix that as well.
Thanks,
David

**Comment by jette** [comment]
The man page (man7/spank.7)  also needs to be updated.

**Comment by supermanue** [comment]
Hi,

Thanks for your suggestions. I have corrected both things.

I included  testplugin/testplugin.c  so you could test this pull request easily. It creates a plugin that can be called with  "--spanktest" flag and employs these new capabilities.  It is not intended to go into Slurm code. Maybe there is some other way of moving this kind of aux files around, but I am not a GIT expert, sorry. 

thanks, 

Manuel

**Comment by jette** [comment]
I only had time to quickly review the patch. You should see Linux kernel coding style information. Anything going into Slurm code base should conform to that. You should follow that going forward. (There is some older code and code from other sources that does not use that formatting, but 99.9% of the code does). See:
http://slurm.schedmd.com/coding_style.pdf

Our next major release is scheduled for May 2016. Any changes to the SPANK API would go into that release.

**Comment by supermanue** [comment]
ok, thanks for the advice. i will review it and format as suggested.

Best regards,

Manuel

2015-10-22 11:33 GMT-07:00 Morris Jette <notifications@github.com>:

> I only had time to quickly review the patch. You should see Linux kernel
> coding style information. Anything going into Slurm code base should
> conform to that. You should follow that going forward. (There is some older
> code and code from other sources that does not use that formatting, but
> 99.9% of the code does). See:
> http://slurm.schedmd.com/coding_style.pdf
>
> Our next major release is scheduled for May 2016. Any changes to the SPANK
> API would go into that release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SchedMD/slurm/pull/134#issuecomment-150315631>.
>



-- 
Dr. Manuel Rodríguez-Pascual
skype: manuel.rodriguez.pascual
phone: (+34) 913466173 // (+34) 679925108

CIEMAT-Moncloa
Edificio 22, desp. 1.25
Avenida Complutense, 40
28040- MADRID
SPAIN

**Comment by dannyauble** [comment]
Please open a bug on this at http://bugs.schedmd.com if you have anything further on this.

**Pull request closed without merging**
