### PR TITLE
allow --ignore-pbs to take effect when read as an #SBATCH argument (14.03 branch)

### PR DESCRIPTION
**Pull request by aaronknister**

### CODE REVIEW

**Comment by jette** [comment]
We are not planning any more releases of Slurm version 14.03. Please use a local patch as needed.

**Comment by aaronknister** [comment]
Moe, it's OK with me that there aren't going to be any more 14.03 releases. I'm requesting these merges so that folks still using the 14.03 release can benefit. I did notice, though, that since this merge request was rejected there have been 7 more commits to the 14.03 branch-- why is this? I would be OK maintaining a local branch if the upstream 14.03 branch were truly dead-- I'd like to avoid duplicating effort.

**Comment by jette** [comment]
The only thing that would likely result in a new v14.03 tag would be a security vulnerability being discovered. The only things being added to v14.03 are serious bugs, but for you I've applied your patch:
https://github.com/SchedMD/slurm/commit/e85d88a9e2fe4adf8204c3d31057ba1acd8f9e73

**Comment by aaronknister** [comment]
Thanks! We appreciate it :)

**Pull request closed without merging**
